services:

  user_api:
    build:
      context: ./user_api
      dockerfile: Dockerfile
    image: user_api:latest
    container_name: user_api
    environment:
      - API_KEY=${API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ALERT_EMAIL=${ALERT_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    volumes:
      - main_volume:/home/app/volume_data

  admin_api:
    build:
      context: ./admin_api
      dockerfile: Dockerfile
    image: admin_api:latest
    container_name: admin_api
    environment:
      - API_KEY=${API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ALERT_EMAIL=${ALERT_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    ports:
      - target: 5100
        published: 5100
        protocol: tcp
        mode: host
    volumes:
      - main_volume:/home/app/volume_data

  inference:
    image: smartrmax/inference:latest
    container_name: inference
    environment:
      - ALERT_EMAIL=${ALERT_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    volumes:
      - main_volume:/home/app/volume_data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  training:
    build:
      context: ./training
      dockerfile: Dockerfile
    image: training:latest
    container_name: training
    environment:
      - ALERT_EMAIL=${ALERT_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    volumes:
      - main_volume:/home/app/volume_data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  preprocessing:
    build:
      context: ./preprocessing
      dockerfile: Dockerfile
    image: preprocessing:latest
    container_name: preprocessing
    environment:
      - ALERT_EMAIL=${ALERT_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - KAGGLE_KEY=${KAGGLE_KEY}
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
    volumes:
      - main_volume:/home/app/volume_data

  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    image: monitoring:latest
    container_name: monitoring
    environment:
      - ALERT_EMAIL=${ALERT_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    volumes:
      - main_volume:/home/app/volume_data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mlflowui:
    build:
      context: ./mlflowui
      dockerfile: Dockerfile
    image: mlflowui:latest
    container_name: mlflowui
    ports:
      - target: 5200
        published: 5200
        protocol: tcp
        mode: host
    volumes:
      - main_volume:/home/app/volume_data

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    image: streamlit:latest
    container_name: streamlit
    environment:
      - STREAMLIT_SERVER_PORT=5300
      - ALERT_EMAIL=${ALERT_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    ports:
      - target: 5300
        published: 5300
        protocol: tcp
        mode: host
    volumes:
      - main_volume:/home/app/volume_data

volumes:
  main_volume:
